# 异常

## 一、异常的概念

**1）基本概念**：java语言中，将程序执行中发生的不正常情况称为异常。

**2）异常可分为两大类：**

①Error（错误）：Java虚拟机无法解决的严重问题。

如：JVM系统内部错误、资源耗尽等严重情况。

②Exception：其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。

如：空指针访问，试图读取不存在的文件，网络连接中断等等。

※Exception分为两大类：<u>运行时异常</u>[程序运行时，发生的异常]，<u>编译时异常</u>[编译时编译器查出的异常]。

## 二、异常体系图

1）运行时异常：编译器检测不出来。一般指编程时的逻辑错误，是程序员应该避免其出现的异常，java.lang.RuntimeException类及它的子类都是运行时异常。

※对于**运行时异常，<u>可以不做处理</u>**，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。

![](https://pic-1317004580.cos.ap-guangzhou.myqcloud.com/%E7%AC%94%E8%AE%B0/11/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%E5%9B%BE.png)

2）**编译时异常：编译器要求<u>必须处置</u>的异常。**



------

![](https://uploadfiles.nowcoder.com/images/20211028/348470426_1635431780619/6479D7BB01736CCC61B8270D41F00B17)

------

> Java语言规范将派生于Error类或RuntimeException类的所有异常称为**非受查（unchecked）异常**，所有其他的异常称为**受查（checked）异常**。

## 三、常见的异常

###1）五大运行时异常：

①【NumberFormatException】数字格式不正确异常：当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式，就会抛出该异常[使用异常我们可以确保输入时满足条件数字]

②【ClassCastException】类型转换异常：当试图将对象强制转换为不是实例的子类时，抛出该异常。

③【ArrayIndexOutOfBoundsException】数组下标越界异常：用非法索引访问数组时抛出该异常，如果索引为负或大于等于数组长度，则该索引为非法索引。

④【ArithmeticException】数学运算异常：当出现异常的运算条件时，抛出该异常。

⑤【NullPointerException】空指针异常：当应用程序试图在需要对象的地方使用null时，抛出该异常。

###2）编译时异常：

①【SQLException】：操作数据库时，查询表可能发生异常

②【IOException】：操作文件时发生的异常

③【FileNotFoundException】：当操作一个不存在的文件时，发生的异常

④【ClassNotFoundException】：加载类，而该类不存在时发生的异常

⑤【EOFException】：操作文件到文件末尾时发生的异常

⑥【IllegalArguementException】：参数异常

## 四、异常处理

###**1）基本介绍**：

异常处理就是当异常发生时，对异常处理的方式



###**2）异常处理的方式：**

①【try-catch-finally】：程序员在代码中捕获发生的异常，自行处理。

②【throws】：将发生的异常抛出，交给调用者（方法）来处理，最顶级的处理者就是JVM。



###**3）throws处理机制图：**

①try-catch-finally和throws二选一

②如果程序员没有显示时处理异常，默认选择throws

![](https://pic-1317004580.cos.ap-guangzhou.myqcloud.com/%E7%AC%94%E8%AE%B0/11/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E5%85%B3%E7%B3%BB%E5%9B%BE.png)

###**4）try-catch-finally处理机制：**

Ⅰ.基本介绍：java提供try和catch块来处理异常，try块用于包含可能出错的代码，catch块用于处理try块中发生的异常，可以根据需要在程序中有许多个try-catch块。

```java
try{
  //代码（可能有异常）
}catch(Exception e){
  //捕获到异常
  //1.当异常发生时
  //2.系统将异常封装成Exception对象e，传递给catch
  //3.得到异常对象后，程序员自行处理
  //4.如果没有发生异常，catch代码块不执行
}finally{
  //1.不管try代码块是否有异常发生，始终要执行finally
  //2.所有通常将释放资源的代码放在finally
}
```

Ⅱ.使用细节：

①如果异常发生了，则异常发生后面的代码不会执行，直接进入到catch块。

②如果异常没有发生，则顺序执行try的代码块，不会进入到catch。

③如果希望不管是否发生异常，都执行某段代码（如关闭连接，释放资源等），则使用finally块

④可以有多个catch语句，捕获不同的异常（进行不同的业务处理），要求父类异常在后，子类异常在前，比如Exception在后，NullPointerException在前），如果发生异常，只会匹配一个catch。

⑤可以进行**try-finally配合使用，这种用法相当于没有捕获异常，因此程序会直接崩掉**。应用场景：执行一段代码，不管是否发生异常，都必须执行某个业务逻辑。

> 假设利用 return 语句从 try语句块中退出。在方法返回前，finally子句的内容将被执行。**如果 finally 子句中也有一个 return语句，这个返回值将会覆盖原始的返回值。**

> try 和 catch 不需要一定共存，try是尝试对其中代码捕获异常，catch是捕获异常并且可以处理异常。你可以 try   来搜寻异常，不去捕获。也就是不去catch   这是可以的。至于提示加finally，finally的意思是，其中的代码一定会执行，也就是说，如果try  其中的代码产生了异常，如果有catch 则会直接跳转到catch部分，如果没有catch  会跳转到‘}’后面的代码，这样，以上方法就没有一个确定的返回值，所以要加finally 作为方法出异常以后的返回的结果。

> 假如try中有异常抛出，则会去执行catch块，再去执行finally块；假如没有catch 块，可以直接执行finally
> 块，方法就以抛出异常的方式结束，而finally 后的内容也不会被执行，所以**catch 和 finally 不能同时省略**。

###**5）throws异常处理**

Ⅰ.基本介绍：

①如果一个方法（中的语句执行时）可能生成某种异常，但是并不确定如何处理这种异常，则此方法应显式地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。

②在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。

Ⅱ.使用细节：

①对于编译异常，程序中必须处理，比如try-catch或者throws

②对于运行时异常，程序中如果没有处理，默认就是throws的方式处理

③子类重写父类的方法时，对抛出异常的规定：子类重写的方法所抛出的异常类型要么和父类抛出的异常一致，要么为父亲抛出的异常的类型的子类型。

④在throws过程中，如果有try-catch，就相当于处理异常，就可以不必throws。

> 应该捕获（**catch**）那些知道如何处理的异常，而将那些不知道怎样处理的异常继续进行传递（**throws**）。

```java
public static void f1() throws FileNotFoundException{
  f3();
}
public static void f3() throws FileNotFoundException{
  FileInputStream fis = new FileInputStream("d://aa.txt");
}
//1、因为f3()方法抛出的是一个编译异常，则这时f1()必须处理整个编译异常
//2、f1()中要么try-catch-finally，或者继续throws这个编译异常
//3、如果f3()抛出的是运行异常，可以不显式处理，因为有默认处理机制
```



### 6）带资源的try语句

```java
//带资源的try语句（try-with-resources）的最简形式
try(Resource res = ...){
  work with res;
}
```

try块退出时，会自动调用res.close()。

```java
//例子
try(Scanner in = new Scanner(new FileInputStream("/usr/share"))){
  while(in.hasNext()){
    System.out.println(in.next());
  }
}
```

> 带资源的try语句自身也可以有catch子句和一个finally子句。这些子句会在关闭资源之后执行。不过在实际中，一个try语句中加入这么多内容可能不是一个好主意。

## 五、自定义异常

1）基本概念：当程序中出现了某些”错误“，但该错误信息并没有在Throwable子类中描述处理，这个时候可以自己设计异常类，用于描述该错误信息。

2）自定义异常步骤：

①定义类：自定义异常类名，继承Exception或RuntimeException

②如果继承Exception，则属于编译异常

③如果继承RuntimeException，则属于运行异常（一般继承RuntimeException）。好处：可以使用默认处理机制



```java
public class CustomException{
  public static void main(String[] args){
    int age = 80;
    if(!(age >= 18 && age <= 120)){
      throw new AgeException("年龄需要在18-120");
    }
    System.out.println("你的年龄范围正确");
  }
}
class AgeException extends RuntimeException{
  public AgeException(String message){//构造器
    super(message);
  }
}
```



※可以用违例（Exception）来抛出一些并非错误的消息，但这样比直接从函数返回一个结果要更大的系统开销。原因：比如我自定义一个异常，若一个变量大于10就抛出一个异常，这样就对应了B选项说的情况，我用抛出异常说明这个变量大于10，而不是用一个函数体（函数体内判断是否大于10，然后返回true或false）判断，**因为函数调用是入栈出栈，栈是在寄存器之下的速度最快，且占的空间少，而自定义异常是存在堆中，肯定异常的内存开销大！**

## 六、throw和throws的对比

对比所在位置，后面跟的东西。【图】

![](https://pic-1317004580.cos.ap-guangzhou.myqcloud.com/%E7%AC%94%E8%AE%B0/11/throw%E5%92%8Cthrows%E7%9A%84%E5%8C%BA%E5%88%AB.png)

>   throw用于抛出异常。 
>   throws关键字可以在方法上声明该方法要抛出的异常，然后在方法内部通过throw抛出异常对象。

> 1、throws出现在方法头，throw出现在方法体
> 2、throws表示出现异常的一种可能性，并不一定会发生异常；throw则是抛出了异常，执行throw则一定抛出了某种异常。
> 3、两者都是消极的异常处理方式，只是抛出或者可能抛出异常，是不会由函数处理，真正的处理异常由它的上层调用处理。





## 补充

###1、try-catch-finally多种情景

> 结论： 1、不管有木有出现异常，finally块中代码都会执行；
> ​    2、当try和catch中有return时，finally仍然会执行；
> ​    3、finally是在return后面的表达式运算后执行的（此时并没有返回运算后的值，而是先把要返回的值保存起来，管finally中的代码怎么样，返回的值都不会改变，任然是之前保存的值），所以函数返回值是在finally执行前确定的；
> ​    4、finally中最好不要包含return，否则程序会提前退出，返回值不是try或catch中保存的返回值。 举例：
>
> 
>
> ***情况1*：try{} catch(){}finally{} return;**
>
> ​            显然程序按顺序执行。
>
> 
>
>
> ***情况2*:try{ return; }catch(){} finally{} return;**
>
>
> ​          程序执行try块中return之前（包括return语句中的表达式运算）代码；
>
>
> ​         再执行finally块，最后执行try中return;
>
> ​         finally块之后的语句return，因为程序在try中已经return所以不再执行。
>
> 
>
>
> ***情况3*:try{ } catch(){return;} finally{} return;**
>
>
> ​         程序先执行try，如果遇到异常执行catch块，
>
>
> ​         有异常：则执行catch中return之前（包括return语句中的表达式运算）代码，再执行finally语句中全部代码，
>
>
> ​                     最后执行catch块中return. finally之后也就是4处的代码不再执行。
>
> ​         无异常：执行完try再finally再return.
>
> 
>
>
> ***情况4*:try{ return; }catch(){} finally{return;}**
>
>
> ​          程序执行try块中return之前（包括return语句中的表达式运算）代码；
>
> ​          再执行finally块，因为finally块中有return所以提前退出。
>
> 
>
>
> ***情况5*:try{} catch(){return;}finally{return;}**
>
>
> ​          程序执行catch块中return之前（包括return语句中的表达式运算）代码；
>
> ​          再执行finally块，因为finally块中有return所以提前退出。
>
> 
>
>
> ***情况6*:try{ return;}catch(){return;} finally{return;}**
>
>
> ​          程序执行try块中return之前（包括return语句中的表达式运算）代码；
>
>
> ​          有异常：执行catch块中return之前（包括return语句中的表达式运算）代码；
>
>
> ​                       则再执行finally块，因为finally块中有return所以提前退出。
>
>
> ​          无异常：则再执行finally块，因为finally块中有return所以提前退出。
>
> 
>
>   最终结论：任何执行try 或者catch中的return语句之前，都会先执行finally语句，如果finally存在的话。
>
>
> ​                  如果finally中有return语句，那么程序就return了，所以finally中的return是一定会被return的，
>
>
> ​                  编译器把finally中的return实现为一个warning。



### 2、使用异常机制的技巧

①异常处理不能代替简单的测试，只在异常情况下使用异常机制。

②不要过分地细化异常

③利用异常层次结构

> 不要只抛出RuntimeException异常。应该寻找更加适当的子类或创建自己的异常类。
>
> 不要只捕获Thowable异常，否则，会使程序代码更难读、更难维护。
>
> 考虑受查异常与非受查异常的区别。已检查异常本来就很庞大，不要为逻辑错误抛出这些异常。
>
> 将一种异常转换成另一种更加适合的异常时不要犹豫。

④不要压制异常

⑤早抛出，晚捕获



### 3、断言

1）介绍

Java 是从 JDK1.4 开始支持断言的，主要**用于程序代码的调试或测试阶段**，千万不能用在正式环境上。当然啦，JVM是默认关闭断言的，想要开启断言还得向 JVM 输入一个参数-enableassertions才可以启用断言，这个后面再讲。

基本的使用就是**assert condition**，当 condition 为 true，就继续往下运行；当 condition 为 false，就抛出一个错误，程序停止。



2）常用方法

①【void setDefaultAssertionStatus(boolean b)】：对于通过类加载器加载的所有类来说，如果没有显式地说明类或包的断言状态，就启用或禁用断言。

②【void setClassAssertionStatus(String className, boolean b)】：对于给定的类和它的内部类，启用或禁用断言。

③【void setPackageAssertionStatus(String packageName, boolean b)】：对于给定包和其子包中的所有类，启用或禁用断言。

④【void clearAssertionStatus()】：移去所有类和包的显式断言状态设置，并禁用所有通过这个类加载器加载的类的断言。

















